name: Generate Snake Animations

on:
  schedule:
    # Atualiza todos os dias às 23h UTC
    - cron: "0 23 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera Snake padrão (modo claro)
      - name: Generate Snake Light
        uses: Platane/snk@v3
        with:
          github_user_name: KelenMachado
          outputs: dist/github-contribution-grid-snake.svg

      # Gera Snake Neon (modo escuro)
      - name: Generate Snake Neon
        uses: Platane/snk@v3
        with:
          github_user_name: KelenMachado
          outputs: dist/github-contribution-grid-snake-neon.svg
          snake_color: neon

      # Gera Snake Dark (modo escuro tradicional)
      - name: Generate Snake Dark
        uses: Platane/snk@v3
        with:
          github_user_name: KelenMachado
          outputs: dist/github-contribution-grid-snake-dark.svg
          color_snake: "#39ff14"
          color_dots: "#1e1e1e,#252526,#2d2d30,#3e3e42,#555555"

      # Publica no branch "output"
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
